SCREEN_FILE_NAME="screen"
SCREEN_FILE_TYPE=".png"
SCREEN_PATH = '{}{}'.format(SCREEN_FILE_NAME,SCREEN_FILE_TYPE)
PC_PROJECT_ROOT="D:\PyPro\kog-money"
PC_CROP_SAVE_PARENT_NAME="screen_crop"
PC_CROP_SAVE_PARENT_PATH="{}\\".format(PC_CROP_SAVE_PARENT_NAME)
PC_RECONGNIZE_TEST="maoxian_crop"
PC_RECONGNIZE_TARGET="maoxian"

